{
  "openapi": "3.0.0",
  "info": {
    "title": "WebStore API",
    "description": "API для заказа товаров из интернет-магазина.\n\nРеализована аутентификация через куки, распределение прав доступа по ролям: гость, пользователь, администратор (помимо своих прав пользователь имеет права гостя, администратор - права гостя и пользователя). Авторизованный пользователь может использовать в запросах только свой логин, администратор - логины всех пользователей.\n\nАдминистратор:\n\nлогин - admin,\n\nпароль - admin.\n\n",
    "version": "1.0.0"
  },
  "paths": {
    "/register": {
      "post": {
        "tags": ["User"],
        "summary": "Регистрация нового пользователя",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "UserName": "john_doe",
                  "Password": "12345",
                  "FirstName": "John",
                  "LastName": "Doe",
                  "PhoneNumber": "+1234567890",
                  "Email": "john@mail.ru"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Пользователь успешно зарегистрирован"
          },
          "400": {
            "description": "Некорректное тело запроса"
          },
          "409": {
            "description": "Логин занят"
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": ["User"],
        "summary": "Вход в аккаунт",
        "parameters": [
          {
            "name": "username",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "password",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Успешный вход в аккаунт"
          },
          "401": {
            "description": "Неверные учетные данные"
          }
        }
      }
    },
    "/logout": {
      "get": {
        "tags": ["User"],
        "summary": "Выход из аккаунта",
        "responses": {
          "200": {
            "description": "Произведен выход из аккаунта"
          },
          "401": {
            "description": "Пользователь не авторизован"
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": ["User"],
        "summary": "Получение списка пользователей",
        "responses": {
          "200": {
            "description": "Список пользователей",
            "content": {
              "application/json": {
                "schema": {
                  "example": [
                    {
                      "userName": "admin",
                      "firstName": "Иван",
                      "lastName": "Иванов",
                      "phoneNumber": "+71112223344",
                      "email": "admin@mail.ru",
                      "isAdmin": true
                    },
                    {
                      "userName": "user",
                      "firstName": "John",
                      "lastName": "Doe",
                      "phoneNumber": "+1234567890",
                      "email": "john@mail.ru",
                      "isAdmin": false
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Пользователь не авторизован"
          },
          "403": {
            "description": "Доступ запрещен"
          }
        }
      }
    },
    "/users/{username}": {
      "get": {
        "tags": ["User"],
        "summary": "Получение информации о пользователе",
        "parameters": [
          {
            "name": "username",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Информация о пользователе",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "401": {
            "description": "Пользователь не авторизован"
          },
          "403": {
            "description": "Доступ запрещен"
          },
          "404": {
            "description": "Пользователь не найден"
          }
        }
      },
      "patch": {
        "tags": ["User"],
        "summary": "Назначение прав администратора пользователю",
        "description": "Доступно только администратору",
        "parameters": [
          {
            "name": "username",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "isAdmin",
            "in": "query",
            "required": true,
            "schema": {
              "type": "boolean"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Права администратора успешно назначены"
          },
          "401": {
            "description": "Пользователь не авторизован"
          },
          "404": {
            "description": "Пользователь не найден"
          }
        }
      },
      "delete": {
        "tags": ["User"],
        "summary": "Удаление пользователя вместе с информацией о его заказах",
        "description": "Доступно только администратору",
        "parameters": [
          {
            "name": "username",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Пользователь удален"
          },
          "401": {
            "description": "Пользователь не авторизован"
          },
          "404": {
            "description": "Пользователь не найден"
          },
          "403": {
            "description": "Доступ запрещен"
          }
        }
      }
    },
    
    "/orders": {
      "get": {
        "tags": ["Order"],
        "summary": "Получение списка заказов",
        "description": "Если указать username, возвращает список заказов пользователя. Если не указывать username, возвращает список всех заказов (доступно только администратору).",
        "parameters": [
          {
            "name": "username",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Список заказов",
            "content": {
              "application/json": {
                "schema": {
                  "example": [
                    {
                      "id": 1,
                      "userName": "admin",
                      "isDone": false
                    },
                    {
                      "id": 2,
                      "userName": "admin",
                      "isDone": true
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Пользователь не авторизован"
          },
          "403": {
            "description": "Доступ запрещен"
          },
          "404": {
            "description": "Пользователь не найден"
          }
        }
      },
      "post": {
        "tags": ["Order"],
        "summary": "Оформление заказа",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "UserName": "admin",
                  "OrderedGoods": [
                    {
                      "goodId": 1001,
                      "amount": 1
                    },
                    {
                      "goodId": 1002,
                      "amount": 2
                    },
                    {
                      "goodId": 1003,
                      "amount": 3
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Заказ создан"
          },
          "400": {
            "description": "Ошибка в теле запроса"
          },
          "401": {
            "description": "Пользователь не авторизован"
          },
          "403": {
            "description": "Доступ запрещен"
          },
          "404": {
            "description": "Пользователь не найден"
          }
        }
      }
    },
    "/orders/{orderId}": {
      "get": {
        "tags": ["Order"],
        "summary": "Получение информации о заказе",
        "parameters": [
          {
            "name": "orderId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Информация о заказе по заданному id",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "id": 1,
                    "userName": "admin",
                    "isDone": false
                  }
                }
              }
            }
          },
          "401": {
            "description": "Пользователь не авторизован"
          },
          "403": {
            "description": "Пользователь не имеет доступа к запрашиваемому ресурсу"
          },
          "404": {
            "description": "Заказ не найден"
          }
        }
      },
      "patch": {
        "tags": ["Order"],
        "summary": "Изменение статуса заказа",
        "description": "Доступно только администратору",
        "parameters": [
          {
            "name": "orderId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "isDone",
            "in": "query",
            "required": true,
            "schema": {
              "type": "boolean"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Статус заказа обновлен"
          },
          "401": {
            "description": "Пользователь не авторизован"
          },
          "403": {
            "description": "Доступ запрещен"
          },
          "404": {
            "description": "Заказ не найден"
          }
        }
      }
    },

    "/orderedGoods": {
      "get": {
        "tags": ["OrderedGoods"],
        "summary": "Получение списка товаров",
        "description": "Если указать id заказа, возвращает список позиций заказа. Если не указывать id, возвращает список всех заказанных товаров (доступно только администратору).",
        "parameters": [
          {
            "name": "OrderId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Список товаров по заданному id заказа",
            "content": {
              "application/json": {
                "schema": {
                  "example": [
                    {
                      "orderId": 1,
                      "goodId": 1001,
                      "amount": 2,
                      "name": "Товар 1",
                      "price": 10
                    },
                    {
                      "orderId": 2,
                      "goodId": 1002,
                      "amount": 1,
                      "name": "Товар 2",
                      "price": 20
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Пользователь не авторизован"
          },
          "403": {
            "description": "Доступ запрещен"
          },
          "404": {
            "description": "Заказ не найден"
          }
        }
      }
    },
    
    "/goods": {
      "get": {
        "tags": ["Goods"],
        "summary": "Получение списка товаров",
        "parameters": [
          {
            "name": "MinPrice",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "MaxPrice",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Список товаров",
            "content": {
              "application/json": {
                "schema": {
                  "example": [
                      {
                        "id": 1001,
                        "name": "Товар 1",
                        "price": 10,
                        "imageUrls": []
                      },
                      {
                        "id": 1002,
                        "name": "Товар 2",
                        "price": 20,
                        "imageUrls": []
                      }
                  ]
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Goods"],
        "summary": "Добавление нового товара",
        "description": "Доступно только администратору",
        "requestBody": 
        {
          "content": 
          {
            "multipart/form-data": 
            {
              "schema": 
              {
                "example": 
                {
                  "Name" : "good name",
                  "Price": 100,
                  "Image": []
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Товар создан"
          },
          "400": {
            "description": "Ошибка в теле запроса"
          },
          "401": {
            "description": "Пользователь не авторизован"
          },
          "403": {
            "description": "Доступ запрещен"
          }
        }
      },
      "put": {
        "tags": ["Goods"],
        "summary": "Обновление товара",
        "description": "Доступно только администратору",
        "requestBody": 
        {
          "content": 
          {
            "multipart/form-data": 
            {
              "schema": 
              {
                "example": 
                {
                  "Id"   : 1001,
                  "Name" : "good name",
                  "Price": 100,
                  "Image": []
                }
              }
            }
          }
        },
        "responses": {
          "200": 
          {
            "description": "Товар обновлен"
          },
          "400": 
          {
            "description": "Ошибка в теле запроса"
          },
          "401": 
          {
            "description": "Пользователь не авторизован"
          },
          "403": 
          {
            "description": "Доступ запрещен"
          },
          "404":
          {
            "description": "Товар не найден"
          }
        }
      }
    },

    "/goods/{goodId}": {
      "get": {
        "tags": [
          "Goods"
        ],
        "summary": "Получение информации о товаре",
        "parameters": [
          {
            "name"    : "goodId",
            "in"      : "path",
            "required": true,
            "schema"  :
            {
              "type": "integer"
            }
          }
        ],
        "responses": 
        {
          "200": 
          {
            "description": "Информация о товаре",
            "content": 
            {
              "application/json": 
              {
                "schema": 
                {
                  "$ref": "#/components/schemas/Good"
                }
              }
            }
          },
          "404":
          {
            "description": "Товар не найден"
          }
        }
      },

      "delete": {
        "tags": ["Goods"],
        "summary": "Удаление товара",
        "description": "Доступно только администратору",
        "parameters": [
          {
            "name"    : "goodId",
            "in"      : "path",
            "required": true,
            "schema"  :
            {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200":
          {
            "description": "Товар удален"
          },
          "401":
          {
            "description": "Пользователь не авторизован"
          },
          "403":
          {
            "description": "Доступ запрещен"
          },
          "404":
          {
            "description": "Товар не найден"
          }
        }
      }
    },

    "/users/{username}/basketItems": {
      "get": {
        "tags": ["BasketItems"],
        "summary": "Получение списка товаров из корзины пользователя",
        "parameters": 
        [
          {
            "name"    : "username",
            "in"      : "path",
            "required": true,
            "schema"  : 
            {
              "type": "string"
            }
          }
        ],
        "responses": 
        {
          "200": 
          {
            "description": "Список товаров из корзины пользователя",
            "content": 
            {
              "application/json": 
              {
                "schema": 
                {
                  "example": 
                  [
                    {
                      "id": "550e8400-e29b-41d4-a716-446655440000",
                      "userName": "john_doe",
                      "goodId": 1001,
                      "amount": 2
                    },
                    {
                      "id": "123e4567-e89b-12d3-a456-426614174000",
                      "userName": "john_doe",
                      "goodId": 1002,
                      "amount": 3
                    }
                  ]
                }
              }
            }
          },
          "401":
          {
            "description": "Пользователь не авторизован"
          },
          "403":
          {
            "description": "Доступ запрещен"
          },
          "404":
          {
            "description": "Пользователь не найден"
          }
        }
      }
    },

    "/users/{username}/basketItems/{goodId}": {
      "get": {
        "tags": ["BasketItems"],
        "summary": "Получение информации о товаре в корзине",
        "parameters": [
          {
            "name"    : "username",
            "in"      : "path",
            "required": true,
            "schema"  :
            {
              "type"  : "string"
            }
          },
          {
            "name"    : "goodId",
            "in"      : "path",
            "required": true,
            "schema"  :
            {
              "type"  : "integer"
            }
          }
        ],
        "responses":
        {
          "200":
          {
            "description": "Информация о товаре в корзине",
            "content":
            {
              "application/json":
              {
                "schema":
                {
                  "$ref": "#/components/schemas/BasketItem"
                }
              }
            }
          },
          "401":
          {
            "description": "Пользователь не авторизован"
          },
          "403":
          {
            "description": "Доступ запрещен"
          },
          "404":
          {
            "description": "Товар в корзине не найден / Пользователь не найден"
          }
        }
      },

      "put": {
        "tags": ["BasketItems"],
        "summary": "Добавление/обновление товара в корзине",
        "parameters": [
          {
            "name"    : "username",
            "in"      : "path",
            "required": true,
            "schema"  :
            {
              "type"  : "string"
            }
          },
          {
            "name"    : "goodId",
            "in"      : "path",
            "required": true,
            "schema"  :
            {
              "type"  : "integer"
            }
          },
          {
            "name"    : "amount",
            "in"      : "query",
            "required": true,
            "schema"  :
            {
              "type"  : "integer"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Товар создан"
          },
          "400": {
            "description": "Ошибка в теле запроса"
          },
          "401": {
            "description": "Пользователь не авторизован"
          },
          "403": {
            "description": "Доступ запрещен"
          }
        }
      },

      "delete": {
        "tags": ["BasketItems"],
        "summary": "Удаление товара из корзины",
        "parameters": [
          {
            "name"    : "username",
            "in"      : "path",
            "required": true,
            "schema"  :
            {
              "type"  : "string"
            }
          },
          {
            "name"    : "goodId",
            "in"      : "path",
            "required": true,
            "schema"  :
            {
              "type"  : "integer"
            }
          }
        ],
        "responses": {
          "200":
          {
            "description": "Товар удален из корзины"
          },
          "401":
          {
            "description": "Пользователь не авторизован"
          },
          "403":
          {
            "description": "Доступ запрещен"
          },
          "404":
          {
            "description": "Товар в корзине не найден / Пользователь не найден"
          }
        }
      }
    }
  },
  
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "UserName": {
            "type": "string"
          },
          "FirstName": {
            "type": "string"
          },
          "LastName": {
            "type": "string"
          },
          "PhoneNumber": {
            "type": "string"
          },
          "Email": {
            "type": "string"
          },
          "IsAdmin": {
            "type": "boolean"
          }
        }
      },
      "Order": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "integer"
          },
          "UserName": {
            "type": "string"
          },
          "IsDone": {
            "type": "boolean"
          }
        }
      },
      "OrderedGood": {
        "type": "object",
        "properties": {
          "OrderId": {
            "type": "integer"
          },
          "GoodId": {
            "type": "integer"
          },
          "Amount": {
            "type": "integer"
          },
          "Name": {
            "type": "string"
          },
          "Price": {
            "type": "number"
          }
        }
      },
      "Good": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "integer"
          },
          "Name": {
            "type": "string"
          },
          "Price": {
            "type": "number"
          },
          "ImageUrls": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "BasketItem": {
        "type": "object",
        "properties": {
          "Id": {
            "type"  : "string",
            "format": "uuid"
          },
          "UserName": {
            "type": "string"
          },
          "GoodId": {
            "type": "integer"
          },
          "Amount": {
            "type": "integer"
          }
        }
      }
    }
  }
}